### ISSUE TITLE
在任何界面点击左上角图标退出登陆

### ISSUE THREAD

**Issue by guliujian** [Njupt-Sast-Network/NICP-Node#2]
![qq20161108-0](https://cloud.githubusercontent.com/assets/10088700/20102847/8c1c75f6-a602-11e6-9e97-008dd4c5abe2.png)

**Comment by sdygt** [comment]
建议首页/team/login/加个session判断什么的，或者把左上角指向/team/news

**Comment by wangxiyu191** [comment]
刚看到。。感觉很有道理。。等下改
